// <auto-generated />
using System;
using ControleDeCaixa.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleDeCaixa.Migrations
{
    [DbContext(typeof(ConnectionContext))]
    [Migration("20241027170758_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControleDeCaixa.Model.Caixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data_abertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Data_fechamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Justificativa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal?>("Valor_final")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Valor_inicial")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Caixa");
                });

            modelBuilder.Entity("ControleDeCaixa.Model.Transacoes", b =>
                {
                    b.Property<int>("Transaca_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Transaca_id"));

                    b.Property<int>("Caixa_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data_transacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tipo_transacao")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal>("valor_transacao")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Transaca_id");

                    b.HasIndex("Caixa_id");

                    b.ToTable("Transacao");
                });

            modelBuilder.Entity("ControleDeCaixa.Model.Transacoes", b =>
                {
                    b.HasOne("ControleDeCaixa.Model.Caixa", "Id")
                        .WithMany()
                        .HasForeignKey("Caixa_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Id");
                });
#pragma warning restore 612, 618
        }
    }
}
